name: My First Workflow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu_latest
    steps:
      - run: echo "Hello World"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in repository 
        run: | 
          echo "The repository ${{ github.repository }} contains the following ➥ files:" 
          tree
